CREATE DATABASE IF NOT EXISTS SIST_PEDIDOS;
USE SIST_PEDIDOS:

CREATE TABLE IF NOT EXIST PRODUCTOS(
    ID_PRODUCTO INT PRYMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION vARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    CANTIDAD INT NOT NULL
 );